version: "cygwin-{build}"

environment:
  matrix:
    - ARCH: x86
#      CYGWIN: C:\Cygwin
#      CYGSH: C:\Cygwin\bin\bash -lc
      PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x" 
      PYTHON_ARCH: "32"

branches:
  except:
    - gh-pages

install:
  - cinst html-help-workshop
  - "%PYTHON% -m pip install -r requirements.txt"

build_script:
  - make clone htmlhelp chm

artifacts:
- path: ags-help.chm
  name: ags-help.chm

deploy:
- provider: GitHub
  auth_token:
    secure: RE/XSZF5WYBi1os9XeUernSQ7znWyIeCUu5m8rzCR/Ocyhmcjoa4N2101UXxtRPr
  artifact: ags-help.chm
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
