name: Build manual

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
        working-directory: ags-manual
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        pandoc:
          - 2.9.1
        shell:
          - bash --noprofile --norc {0}
          - sh {0}
    steps:
      - name: Checkout build system
        uses: actions/checkout@v2
        with:
          path: ags-manual
      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: morganwillcock/ags-manual.wiki
          path: ags-manual.wiki
      - name: Set path to Markdown files
        working-directory: ags-manual.wiki
        run: echo "CHECKOUTDIR=$(pwd)" >> $GITHUB_ENV
      - name: Get Markdown files
        run: make source
      - name: Download Pandoc
        run: |
          case "${{ runner.os }}" in
            Linux)
              pandoc="pandoc-${{ matrix.pandoc }}/bin/pandoc"
              suffix=linux-amd64.tar.gz
              tar=tar
              ;;
            macOS)
              pandoc="pandoc-${{ matrix.pandoc }}/bin/pandoc"
              suffix=macOS.zip
              tar=bsdtar
              ;;
            Windows)
              pandoc=pandoc.exe
              suffix=windows-x86_64.zip
              tar=/c/Windows/System32/tar.exe
              ;;
            *)
              exit 1
              ;;
          esac
          url="https://github.com/jgm/pandoc/releases/download/${{ matrix.pandoc }}/pandoc-${{ matrix.pandoc }}-$suffix"
          curl -fL "$url" | $tar -f - -vxzC "${{ runner.temp }}" "$pandoc"
          chmod +x "${{ runner.temp }}/$pandoc"
          echo PANDOC="${{ runner.temp }}/$pandoc" >> $GITHUB_ENV
      - name: Check Markdown files
        run: (! make -j $(getconf _NPROCESSORS_ONLN) metacheck 2>&1 >/dev/null | grep ^ERROR)
      - name: Build website
        run: make -j $(getconf _NPROCESSORS_ONLN) html
      - name: Build HTML Help Project
        run: make -j $(getconf _NPROCESSORS_ONLN) htmlhelp
