name: Build manual

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
        working-directory: ags-manual
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        pandoc:
          - 2.9.1
        shell:
          - bash
          - sh
    steps:
      - name: Checkout build system
        uses: actions/checkout@v2
        with:
          path: ags-manual
      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: morganwillcock/ags-manual.wiki
          path: ags-manual.wiki
      - name: Set path to Markdown files
        working-directory: ags-manual.wiki
        run: echo "CHECKOUTDIR=$(pwd)" >> $GITHUB_ENV
      - name: Get Markdown files
        run: make source
      - name: Download and install Pandoc
        run: |
          case "${{ runner.os }}" in
            Linux)
              pandoc="pandoc-${{ matrix.pandoc }}/bin/pandoc"
              suffix=linux-amd64.tar.gz
              tar=tar
              ;;
            macOS)
              pandoc="pandoc-${{ matrix.pandoc }}/bin/pandoc"
              suffix=macOS.zip
              tar=bsdtar
              ;;
            Windows)
              pandoc=pandoc.exe
              suffix=windows-x86_64.zip
              tar=/c/Windows/System32/tar.exe
              ;;
            *)
              exit 1
              ;;
          esac
          url="https://github.com/jgm/pandoc/releases/download/${{ matrix.pandoc }}/pandoc-${{ matrix.pandoc }}-$suffix"
          curl -fL "$url" | $tar -f - -vxzC "${{ runner.temp }}" "$pandoc"
          chmod +x "${{ runner.temp }}/$pandoc"
          echo PANDOC="${{ runner.temp }}/$pandoc" >> $GITHUB_ENV
      - name: Check Markdown files
        run: |
          set +e
          (! make -j $(getconf _NPROCESSORS_ONLN) metacheck 2>&1 >/dev/null | grep ^ERROR)
      - name: Build website
        run: make -j $(getconf _NPROCESSORS_ONLN) html
      - name: Upload website
        uses: actions/upload-artifact@v2
        with:
          name: html (${{ matrix.os }}-${{ matrix.shell }})
          path: ags-manual/html/build
          if-no-files-found: error
      - name: Build HTML Help Project
        run: make -j $(getconf _NPROCESSORS_ONLN) htmlhelp
      - name: Upload HTML Help Project
        uses: actions/upload-artifact@v2
        with:
          name: htmlhelp (${{ matrix.os }}-${{ matrix.shell }})
          path: ags-manual/htmlhelp/build
          if-no-files-found: error
      - name: Download and install HTML Help Workshop
        if: startsWith(matrix.os, 'windows-')
        shell: cmd
        env:
          CHECKSUM: b2b3140d42a818870c1ab13c1c7b8d4536f22bd994fa90aade89729a6009a3ae
          HHC: C:\Program Files (x86)\HTML Help Workshop\hhc.exe
          URL: https://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe
        run: |
          %COMSPEC% /c "pushd "${{ runner.temp }}" && curl -fLOJ "%URL%"" || exit /b 1

          for /f %%a in ('certutil -hashfile "${{ runner.temp }}\htmlhelp.exe" SHA256 ^| find /v " "') do set SHA256=%%a
          if not "%SHA256%" == "%CHECKSUM%" exit /b 1

          "${{ runner.temp }}\htmlhelp.exe" /Q /T:"${{ runner.temp }}\htmlhelp" /C
          > "${{ runner.temp }}\htmlhelp\htmlhelp_noupdate.inf" findstr /v /b """hhupd.exe "${{ runner.temp }}\htmlhelp\htmlhelp.inf"
          %SYSTEMROOT%\SysWOW64\rundll32.exe advpack.dll,LaunchINFSection "${{ runner.temp }}\htmlhelp\htmlhelp_noupdate.inf",,3,N
          if not exist "%HHC%" exit /b 1

          echo HHC=%HHC%>> %GITHUB_ENV%
      - name: Build CHM file
        if: env.HHC
        run: make chm
      - name: Upload CHM file
        if: env.HHC
        uses: actions/upload-artifact@v2
        with:
          name: ags-help.chm (${{ matrix.os }}-${{ matrix.shell }})
          path: ags-manual/htmlhelp/build/ags-help.chm
          if-no-files-found: error
