name: Build manual

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
        working-directory: ags-manual
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        pandoc:
          - 2.9.1
        shell:
          - bash
          - sh
    steps:
      - name: Checkout build system
        uses: actions/checkout@v2
        with:
          path: ags-manual
      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: morganwillcock/ags-manual.wiki
          path: ags-manual.wiki
      - name: Set path to Markdown files
        working-directory: ags-manual.wiki
        run: echo "CHECKOUTDIR=$(pwd)" >> $GITHUB_ENV
      - name: Get Markdown files
        run: make source
      - name: Download and install Pandoc
        run: |
          case "${{ runner.os }}" in
            Linux)
              pandoc="pandoc-${{ matrix.pandoc }}/bin/pandoc"
              suffix=linux-amd64.tar.gz
              tar=tar
              ;;
            macOS)
              pandoc="pandoc-${{ matrix.pandoc }}/bin/pandoc"
              suffix=macOS.zip
              tar=bsdtar
              ;;
            Windows)
              pandoc=pandoc.exe
              suffix=windows-x86_64.zip
              tar=/c/Windows/System32/tar.exe
              ;;
            *)
              exit 1
              ;;
          esac
          url="https://github.com/jgm/pandoc/releases/download/${{ matrix.pandoc }}/pandoc-${{ matrix.pandoc }}-$suffix"
          curl -fL "$url" | $tar -f - -vxzC "${{ runner.temp }}" "$pandoc"
          chmod +x "${{ runner.temp }}/$pandoc"
          echo PANDOC="${{ runner.temp }}/$pandoc" >> $GITHUB_ENV
      - name: Check Markdown files
        run: |
          set +e
          (! make -j $(getconf _NPROCESSORS_ONLN) metacheck 2>&1 >/dev/null | grep ^ERROR)
      - name: Build website
        run: make -j $(getconf _NPROCESSORS_ONLN) html
      - name: Upload website
        uses: actions/upload-artifact@v2
        with:
          name: html (${{ matrix.os }}-${{ matrix.shell }})
          path: ags-manual/html/build
          if-no-files-found: error
      - name: Build HTML Help Project
        run: make -j $(getconf _NPROCESSORS_ONLN) htmlhelp
      - name: Upload HTML Help Project
        uses: actions/upload-artifact@v2
        with:
          name: htmlhelp (${{ matrix.os }}-${{ matrix.shell }})
          path: ags-manual/htmlhelp/build
          if-no-files-found: error
      - name: Download and install HTML Help Workshop
        if: startsWith(matrix.os, 'windows-')
        shell: cmd
        env:
          HHC: C:\Program Files (x86)\HTML Help Workshop\hhc.exe
        run: |
          call scripts\install_hhw.cmd
          if exist "%HHC%" echo HHC=%HHC%>> %GITHUB_ENV%
      - name: Build CHM file
        if: env.HHC
        run: make chm
      - name: Upload CHM file
        if: env.HHC
        uses: actions/upload-artifact@v2
        with:
          name: ags-help.chm (${{ matrix.os }}-${{ matrix.shell }})
          path: ags-manual/htmlhelp/build/ags-help.chm
          if-no-files-found: error
